[build]
command = 'bun run build'

[dev]
port = 8888

[[headers]]
for = '/*'
[headers.values]
content-security-policy = "default-src 'self'; font-src 'self'; frame-ancestors 'self'; img-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
permissions-policy = 'camera=(), microphone=(), geolocation=()'
referrer-policy = 'strict-origin-when-cross-origin'
x-content-type-options = 'nosniff'
x-frame-options = 'sameorigin'

[[headers]]
for = '/_astro/*'
[headers.values]
cache-control = 'public, max-age=31536000, immutable'
